# ZikeQuote3 配置文件
# 如有修改，注意调整 `config.py` 中的配置模型

[general]
enable_zikequote3 = true # 总开关
enable_groups = [] # 启用插件的群列表
check_intergrity = true # 启动时检查 Node.js 依赖完整性

[collecting]
enable_auto_collect = true # 启用自动收集，需要配置 LLM
pickup_interval = 80 # 自动收集触发的消息数量阈值
msg_max_length = 35 # 最大可被处理的消息长度
at_least_selections = 0 # 要求 LLM 给出的筛选结果个数下限
at_most_selections = 3 # 要求 LLM 给出的筛选结果个数上限
enable_duplicate = false # 允许群内个人重复语录
enable_image_collection = true # 允许图片语录收集
img_max_sidelength = 3840 # 允许收集的图片最大边长，单位 px，超出会被裁剪
img_max_size_mb = 5 # 允许收集的图片最大体积，单位 MB
update_personal_info_probability = 0.05 # 收到消息时更新个人信息的概率

[fetching]
enable_cross_group_fetching = false # 允许跨群抓取调用者个人语录
algorithm = "freq" # 语录推荐算法: freq | diversity (TODO)

[showcase]
max_rank_user_num = 40 # 语录榜单展示最大用户数
quote_num_per_page = 20 # 语录展示每页数量
page_num_limit = 5 # 语录展示最大页数
comment_show_method = "noai" # 语录评论展示方式: no | noai | all
hitokoto_url = "https://v1.hitokoto.cn" # 获取名人名言 Hitokoto API
render_device_factor = 2.0 # 图片渲染设备像素比

[permission]
static_root = [] # 不可变最高权限 QQ 号列表，List[int]

[llm]
# 模型配置较为复杂，其它端点调整工作需到 llm_services/client.py 进行修改
base_url = "https://openrouter.ai/api/v1"
api_key_path = "llm_services/api_key" # API Key 文件路径，相对插件根目录或绝对路径
model = "deepseek/deepseek-v3.2-exp"
temperature = 0.2
max_retries = 3 # 请求失败重试次数

[sentry]
dsn_path = "utils/sentry_dsn" # Sentry DSN 文件路径，相对插件根目录或绝对路径，可留空表示不启用

[configure]
# 不允许进行热更新，并且应该全局应用的配置项
nonreloadable_items = [
    "general.enable_zikequote3",
    "general.enable_groups",
    "general.check_intergrity",
    "permission.static_root",
    "llm.api_key_path",
    "sentry.dsn_path",
    "configure.nonreloadable_items",
]