"""initial_schema

Revision ID: 9a62ce7e5cff
Revises: 
Create Date: 2026-02-10 11:25:34.846843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a62ce7e5cff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('images',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('checksum_sha256', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('qq_id', sa.String(), nullable=False),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('qq_id')
    )
    op.create_table('group_configs',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('toml_config', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('qq_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qq_id'], ['users.qq_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'qq_id')
    )
    op.create_table('group_nicknames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qq_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('current_using', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['qq_id'], ['users.qq_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msgs_queue',
    sa.Column('msg_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('qq_id', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qq_id'], ['users.qq_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('queue_group_message_counts',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('quotes',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_content_uuid', sa.String(), nullable=True),
    sa.Column('total_show_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.qq_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['image_content_uuid'], ['images.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_table('user_nicknames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qq_id', sa.String(), nullable=False),
    sa.Column('current_using', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qq_id'], ['users.qq_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msgid_quoteid_map',
    sa.Column('msg_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.qq_id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('msgid_quoteid_map')
    op.drop_table('user_nicknames')
    op.drop_table('quotes')
    op.drop_table('queue_group_message_counts')
    op.drop_table('msgs_queue')
    op.drop_table('group_nicknames')
    op.drop_table('group_members')
    op.drop_table('group_configs')
    op.drop_table('users')
    op.drop_table('images')
    op.drop_table('groups')
    # ### end Alembic commands ###
